export const NAV_ITEMS = [
  { href: "/", label: "首页" },
  { href: "/stories", label: "文章札记" },
  { href: "/forum", label: "论坛聊天室" },
  { href: "/anonymous", label: "匿名板" },
  { href: "/admin", label: "管理界面" },
  { href: "/space", label: "个人空间" },
  { href: "/gallery", label: "展示墙" },
] as const;

export const DEFAULT_PUBLIC_PROFILE_USERNAME = "rubedo_room";

export const SPACE_SHOWCASE_GROUPS = [
  {
    id: "anime",
    label: "动画",
    items: [
      {
        id: "anime-1",
        title: "CLANNAD",
        subtitle: "Key / 京都动画",
        note: "家族线与情绪推进节奏几乎完美。",
        image: "/bg1.png",
        originalTitle: "クラナド",
        score: 9.2,
        rank: 26,
        releaseYear: 2007,
        episodes: 23,
        collectionStatus: "collect",
      },
      {
        id: "anime-2",
        title: "AIR",
        subtitle: "Key / 京都动画",
        note: "夏天、海风与久别重逢的旧梦。",
        image: "/bg2.png",
        originalTitle: "AIR",
        score: 8.4,
        rank: 318,
        releaseYear: 2005,
        episodes: 12,
        collectionStatus: "collect",
      },
      {
        id: "anime-3",
        title: "Angel Beats!",
        subtitle: "P.A.WORKS",
        note: "想补一遍音乐线和群像收束。",
        image: "/bg1.png",
        originalTitle: "Angel Beats!",
        score: 7.9,
        rank: 1020,
        releaseYear: 2010,
        episodes: 13,
        collectionStatus: "wish",
      },
      {
        id: "anime-4",
        title: "Kanon",
        subtitle: "京都动画",
        note: "还在慢慢重看雪夜支线。",
        image: "/bg2.png",
        originalTitle: "Kanon",
        score: 8.1,
        rank: 742,
        releaseYear: 2006,
        episodes: 24,
        collectionStatus: "doing",
      },
      {
        id: "anime-5",
        title: "Charlotte",
        subtitle: "P.A.WORKS",
        note: "中段推进有点急，先搁置。",
        image: "/bg1.png",
        originalTitle: "Charlotte",
        score: 7.1,
        rank: 2018,
        releaseYear: 2015,
        episodes: 13,
        collectionStatus: "on_hold",
      },
    ],
  },
  {
    id: "books",
    label: "书籍",
    items: [
      {
        id: "book-1",
        title: "All You Need Is Kill",
        subtitle: "桜坂洋",
        note: "单册完成度很高，节奏利落。",
        image: "/bg2.png",
        originalTitle: "All You Need Is Kill",
        score: 8.7,
        rank: 110,
        releaseYear: 2004,
        pages: 247,
        collectionStatus: "collect",
      },
      {
        id: "book-2",
        title: "人间失格",
        subtitle: "太宰治",
        note: "标注了很多段落，准备二刷。",
        image: "/bg1.png",
        originalTitle: "人間失格",
        score: 8.2,
        rank: 436,
        releaseYear: 1948,
        pages: 176,
        collectionStatus: "collect",
      },
      {
        id: "book-3",
        title: "三体",
        subtitle: "刘慈欣",
        note: "计划按部重读，先挂愿望单。",
        image: "/bg2.png",
        originalTitle: "三体",
        score: 9.0,
        rank: 72,
        releaseYear: 2006,
        pages: 302,
        collectionStatus: "wish",
      },
      {
        id: "book-4",
        title: "白夜行",
        subtitle: "东野圭吾",
        note: "读到中段，人物关系线很强。",
        image: "/bg1.png",
        originalTitle: "白夜行",
        score: 8.9,
        rank: 98,
        releaseYear: 1999,
        pages: 538,
        collectionStatus: "doing",
      },
    ],
  },
  {
    id: "games",
    label: "游戏",
    items: [
      {
        id: "game-1",
        title: "CLANNAD",
        subtitle: "Key",
        note: "通完主线后一直在做角色线补档。",
        image: "/bg1.png",
        originalTitle: "CLANNAD",
        score: 9.5,
        rank: 12,
        releaseYear: 2004,
        hours: "68h",
        collectionStatus: "collect",
      },
      {
        id: "game-2",
        title: "Summer Pockets",
        subtitle: "Key",
        note: "准备暑假开坑，先放想玩列表。",
        image: "/bg2.png",
        originalTitle: "Summer Pockets",
        score: 8.6,
        rank: 205,
        releaseYear: 2018,
        hours: "未开始",
        collectionStatus: "wish",
      },
      {
        id: "game-3",
        title: "Rewrite",
        subtitle: "Key",
        note: "目前在 Terra 线，进度偏慢。",
        image: "/bg1.png",
        originalTitle: "Rewrite",
        score: 8.8,
        rank: 140,
        releaseYear: 2011,
        hours: "42h",
        collectionStatus: "doing",
      },
      {
        id: "game-4",
        title: "planetarian",
        subtitle: "Key",
        note: "短篇很扎实，准备补全语音版。",
        image: "/bg2.png",
        originalTitle: "planetarian ～ちいさなほしのゆめ～",
        score: 8.3,
        rank: 380,
        releaseYear: 2004,
        hours: "5h",
        collectionStatus: "collect",
      },
      {
        id: "game-5",
        title: "神様になった日",
        subtitle: "visual novel adaptation",
        note: "改编节奏不稳，暂时弃置。",
        image: "/bg1.png",
        originalTitle: "神様になった日",
        score: 6.4,
        rank: 3910,
        releaseYear: 2021,
        hours: "12h",
        collectionStatus: "dropped",
      },
    ],
  },
] as const;

export const SPACE_FRIENDS = [
  {
    id: "friend-real-rubedo-room",
    name: "Rubedo Room",
    username: "rubedo_room",
    status: "在线",
    isReal: true,
    note: "真实账号好友，来源于站内公开资料 `/users/rubedo_room`。",
  },
  {
    id: "friend-1",
    name: "纸窗旅人",
    username: "paper_window_traveler",
    status: "在线",
    isReal: false,
    note: "常在剧情讨论区出没，偏爱慢热叙事。",
  },
  {
    id: "friend-2",
    name: "留白观察者",
    username: "blank_observer",
    status: "离线",
    isReal: false,
    note: "喜欢整理收藏架和空间展示方式。",
  },
  {
    id: "friend-3",
    name: "夜航编辑部",
    username: "night_editorial",
    status: "忙碌",
    isReal: false,
    note: "经常写札记，也会参与共赏会整理。",
  },
] as const;

export const SPACE_TIME_CAPSULES = [
  {
    id: "capsule-1",
    title: "大一跨年夜",
    time: "2024.12",
    command: "capsule.pack --assets screenshot,group-shot,message --tag freshman-newyear",
    record: "行为记录：上传截图、归档群像、封存留言。",
    body: "把那次深夜闪闪发光的截图、群像和留言封进一个时间胶囊里。",
  },
  {
    id: "capsule-2",
    title: "第一次共赏会",
    time: "2025.03",
    command: "watchparty.parse --focus character-view,dialogue --session first-screening",
    record: "行为记录：从角色视角拆解并标注关键对白，沉淀讨论节奏。",
    body: "从角色视角和对白拆解开始，第一次感觉社团真的有了自己的讨论节奏。",
  },
  {
    id: "capsule-3",
    title: "展墙初次成型",
    time: "2025.11",
    command: "wall.compose --assets image,paper,polaroid,music --layout v1",
    record: "行为记录：把图片、旧纸、拍立得和音乐统一编排到同一面墙。",
    body: "把图片、旧纸、拍立得和音乐放到同一面墙上的那天，空间终于像空间了。",
  },
] as const;
